Test
KwanV92/port_allocations pull request #4
Opened 2024-05-14 15:31 UTC by TomCohenAbeille

feat : test if the constraints file is valid (with MIN_EXPO, MAX_EXPO, STEP)

2024-05-14 16:44 UTC, KwanV92 requested changes
- De bonnes améliorations et une bonne gestion des cas de mauvais csv
- Quelques naming à modifier
- Des portions de code à modifier

2024-05-14 16:44 UTC, KwanV92 commented on main.py
> +    compute_possible_allocations(dataframe)
tu fais les deux étapes en une seule mais imaginons que demain on a juste besoin du nombre d'allocations possibles avant de pouvoir lancer notamment nos calculs de frontière efficiente ? Je pense que ce serait bien de découper la fonction compute possible allocations

2024-05-14 16:44 UTC, KwanV92 commented on main.py
> +        "C:/Users/S084870/OneDrive - Abeille Assurances/Bureau/TOM/Projet/port_allocation/port_allocations/input/constraints.csv"
a-t-on vraiment besoin d'indiquer le chemin depuis la racine ? sys.path ne nous a-t-il pas positionné dans le dossier port_allocations ?

2024-05-14 16:44 UTC, KwanV92 commented on computationals.py
> +    detailled_weight: list = []
naming : detailed un seul l

2024-05-14 16:44 UTC, KwanV92 commented on computationals.py
> +    steps = np.delete(steps, 0)
Ok je vois l'idée, je vais te proposer une autre approche tu me diras ce que tu en penses

2024-05-14 16:44 UTC, KwanV92 commented on computationals.py
> +        asset_possible_weight: list = []
naming : j'aurais mis un "s" a weight pour bien expliciter que l'on en a plusieurs, on comprend alors plus rapidement que c'est une liste
J'imagine que tu te dis que je pinaille, mais le naming des variables est une grosse partie du travail du développeur

2024-05-14 16:44 UTC, KwanV92 commented on computationals.py
> +    detailled_weight: list = []
naming : et manque de clarté aussi dans le nom choisi de la variable, c'est peut etre juste mon avis, on pourrait demander a quelqu'un d'autre au bureau pour voir

2024-05-14 16:44 UTC, KwanV92 commented on computationals.py
> +    for assets in product(*detailed_steps):
je ne comprends toujours pas pourquoi tu veux utiliser la variable assets dans un itérateur de boucle for, on en discute ensemble avec un schéma ça sera peut etre plus parlant

2024-05-14 16:44 UTC, KwanV92 commented on main.py
> +    compute_possible_allocations(dataframe)
après lecture de tout le code, effectivement tu n'affiches jamais le nombre d'allocations possibles comme demandé dans l'étape 2

2024-05-15 07:19 UTC, TomCohenAbeille commented on main.py
> +        "C:/Users/S084870/OneDrive - Abeille Assurances/Bureau/TOM/Projet/port_allocation/port_allocations/input/constraints.csv"
quand j'ai créé les 3 dossiers input/output/src, j'ai mis le csv dans le file input et vscode ne le trouvais pas juste en indiquant le nom, j'ai donc du indiqué tout le chemin

2024-05-15 12:14 UTC, closed without merging